post?: 
type: successReturned
get: 
  description: "You can see which users are 'attending' an event by issuing an HTTP GET to /EVENT_ID/attending This returns a list of all users who responded 'yes' to the event"
  responses: 
    200: 
      body: 
        application/json: 
          schema: attending
