get?: 
  responses: 
    400: 
      description: |
        458 App Not Installed
        The user has not logged into your app, try logging them in again.
        459 User Checkpointed
        Person needs to log onto www.facebook.com, or m.facebook.com to correct issue.
        460 Password Changed
        On iOS 6 and above, if the person logged in using the OS-integrated flow, they should be directed to Facebook OS settings on the device to update their password. 
        Otherwise they must login to the app again.
        463 Expired
        Login status or access token has expired, been revoked, or is otherwise invalid - Handle expired access tokens.
        464 Unconfirmed User
        Person needs to log onto www.facebook.com, or m.facebook.com to correct issue.
        467 Invalid access token
        Access token has expired, been revoked, or is otherwise invalid - Handle expired access tokens.
      body: 
        application/json: 
          schema: error
          example: !include examples/error-example.json
post?: 
  queryParameters: 
    method: 
      description: |
        "To support clients that do not support all HTTP methods, you can alternatively issue a POST request to an endpoint with the 
        additional argument method=delete to override the HTTP method."
      enum: 
        - delete
        - put
        - get
        - patch
  responses: 
    400: 
      description: |
        458 App Not Installed
        The user has not logged into your app, try logging them in again.
        459 User Checkpointed
        Person needs to log onto www.facebook.com, or m.facebook.com to correct issue.
        460 Password Changed
        On iOS 6 and above, if the person logged in using the OS-integrated flow, they should be directed to Facebook OS settings on the device to update their password. 
        Otherwise they must login to the app again.
        463 Expired
        Login status or access token has expired, been revoked, or is otherwise invalid - Handle expired access tokens.
        464 Unconfirmed User
        Person needs to log onto www.facebook.com, or m.facebook.com to correct issue.
        467 Invalid access token
        Access token has expired, been revoked, or is otherwise invalid - Handle expired access tokens.
      body: 
        application/json: 
          schema: error
          example: !include examples/error-example.json
delete?: 
  responses: 
    400: 
      description: |
        458 App Not Installed
        The user has not logged into your app, try logging them in again.
        459 User Checkpointed
        Person needs to log onto www.facebook.com, or m.facebook.com to correct issue.
        460 Password Changed
        On iOS 6 and above, if the person logged in using the OS-integrated flow, they should be directed to Facebook OS settings on the device to update their password. 
        Otherwise they must login to the app again.
        463 Expired
        Login status or access token has expired, been revoked, or is otherwise invalid - Handle expired access tokens.
        464 Unconfirmed User
        Person needs to log onto www.facebook.com, or m.facebook.com to correct issue.
        467 Invalid access token
        Access token has expired, been revoked, or is otherwise invalid - Handle expired access tokens.
      body: 
        application/json: 
          schema: error
          example: !include examples/error-example.json
