post?: 
  responses: 
    200: 
      body: 
        application/json: 
          schema: id
          example: !include examples/id-example.json
delete?: 
  responses: 
    200: 
      body: 
        application/json: 
          schema: id
          example: !include examples/id-example.json
type: base
