type: successReturned
description: The posts and links published by this person or others on their profile.
get: 
  description: Return an array of Post objects.
  queryParameters: 
    with: 
      description: Restrict the list of posts to only those with location attached.
      enum: [ location ]
      example: with=location
    filter: 
      description: Retrieve only posts that match a particular stream filter. Valid filters to be used here can be retrieved using the FQL stream_filter table.
  responses: 
    200: 
      body: 
        application/json: 
          schema: posts
post: 
  description: You can create links, status messages, or posts by using this edge
  body: 
    multipart/form-data: 
      formParameters: 
        message: 
          description: The main body of the post, otherwise called the status message. Either link or message must be supplied.
          example: message=This+is+a+test+message
        link: 
          description: The URL of a link to attach to the post. Either link or message must be supplied. Additional fields associated with link are shown below.
