post?: 
  responses: 
    200: 
      body: 
        application/json: 
          schema: success
          example: !include examples/success-example.json
delete?: 
  responses: 
    200: 
      body: 
        application/json: 
          schema: success
          example: !include examples/success-example.json
type: base
