queryParameters: 
  fields: 
    description: |
      The /{user-id} node has more complicated permissions requirements than other nodes in the Graph API:
      There are a number of fields called the public profile which are always available with no access token.
      Other fields that have been explicitly set to public visibility can also be retrieved without an access token.
      Fields that aren't set to public must be be requested with an access token, and if necessary the token must have the relevant 'Extended Profile' permissions.
