queryParameters: 
  offset: 
    description: This offsets the start of each page by the number specified.
  limit: 
    description: This is the number of individual objects that are returned in each page. A limit of 0 will return no results.
